# -*- coding: utf-8 -*-
"""sales forecasting analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vBg3HUh7VpaimL-H2JHndDkNK8-q8eS
"""

!pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random
import matplotlib.pyplot as plt
import seaborn as sns

fake = Faker()

stores = ['Store_A', 'Store_B', 'Store_C', 'Store_D']
items = ['Product_1', 'Product_2', 'Product_3', 'Product_4', 'Product_5']
regions = ['North', 'South', 'East', 'West']

data = []

for i in range(100000):
    date = fake.date_between(start_date='-2y', end_date='today')
    store = random.choice(stores)
    item = random.choice(items)
    region = random.choice(regions)
    sales = random.randint(10, 500)

    data.append([date, store, item, region, sales])

columns = ['Date', 'Store', 'Item', 'Region', 'Sales']

df = pd.DataFrame(data, columns=columns)

df.head()

df['Date'] = pd.to_datetime(df['Date'])


print(df.isnull().sum())


df = df.drop_duplicates()

df.info()

print(df.describe())

daily_sales = df.groupby('Date')['Sales'].sum()

plt.figure(figsize=(10,5))
plt.plot(daily_sales.index, daily_sales.values)
plt.title("Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

df['Month'] = df['Date'].dt.to_period('M')

monthly_sales = df.groupby('Month')['Sales'].sum()

monthly_sales.plot(kind='line', figsize=(10,5))
plt.title("Monthly Sales Trend")
plt.show()

store_sales = df.groupby('Store')['Sales'].sum()

store_sales.plot(kind='bar')
plt.title("Sales by Store")
plt.show()

plt.hist(df['Sales'])
plt.title("Sales Distribution")
plt.show()

sns.boxplot(x=df['Sales'])
plt.title("Sales Outliers")
plt.show()

df_encoded = df.copy()
df_encoded['Store'] = df_encoded['Store'].astype('category').cat.codes
df_encoded['Item'] = df_encoded['Item'].astype('category').cat.codes
df_encoded['Region'] = df_encoded['Region'].astype('category').cat.codes

plt.figure(figsize=(8,5))
sns.heatmap(df_encoded.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()